name: CI - Batida de Ponto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências (frontend)
        run: |
          cd frontend
          npm install

      - name: Lint (frontend)
        run: |
          cd frontend
          npm run lint

      - name: Build (frontend)
        run: |
          cd frontend
          npm run build

      - name: Testes (frontend)
        run: |
          cd frontend
          npm test

  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: clock_in_go_user
          POSTGRES_PASSWORD: senhaSegura123
          POSTGRES_DB: clock_in_go_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências (backend)
        run: |
          cd backend
          npm install

      - name: Lint (backend)
        run: |
          cd backend
          npm run lint

      - name: Testes (backend)
        run: |
          cd backend
          npm test
